### ISSUE TITLE
Store the top k most frequently opened papers in the last Y days into the cache

### ISSUE THREAD

**Issue by zc-alexfan** [vict0rsch/PaperMemory#101]
**Is your feature request related to a problem? Please describe.**
It is a bit repetitive to download paper PDFs into the cache folder for a set of papers that we often need to open during a given period.

**Describe the solution you'd like**
Can we have an option to store the top k most frequently opened papers in the last Y days into the cache? (Maybe also optionally allow another set of papers to be always in the cache) This is handy for people who only need to search for something specific in a paper, as we don't need to wait for the paper to be downloaded every time.

**Comment by vict0rsch** [comment]
Hey! Thank you for your thoughts!

I'm not sure I understand, could you elaborate? Do you mean to *automatically* download papers? 

Right now the cache is used for any paper you download using PM, including using the download keyboard shortcut (#92). I'm not sure I understand what you mean by

>  store the top k most frequently opened papers in the last Y days into the cache

Do you mean something like (pseudo-code)

```python
if today_is_a_new_day:
    top_k_papers = find_most_opened_papers(top=k)
    cached_papers = load_paper_memory_store()
    for paper in memory_papers:
        if paper in top_k_papers and paper not in cached_papers:
            download_to_paper_memory_store(paper)
```

**Comment by zc-alexfan** [comment]
Yes, exactly. Because in a given period of time, we often have a list of papers we need to refer to. Caching those papers automatically, would allow us to open them up without waiting for the arxiv downloads.

**Comment by vict0rsch** [comment]
But currently you only have to wait for the Arxiv download once, if you `ctrl/cmd + shift + s` on the paper's page the paper will be downloaded to the cache (`~/Downloads/PaperMemoryStore`) and next times you can use that cached version.

In that context, that algorithm is very marginally more efficient than you choosing to download a paper from its page, is it not?

**Comment by zc-alexfan** [comment]
I see. That makes sense. Thanks.
