### ISSUE TITLE
Show a list of saved tags

### ISSUE THREAD

**Issue by pviscone** [vict0rsch/PaperMemory#114]
It could be useful to have a drop-down menu (or something similar) to show all the tags used and to select one or more tags to filter the search.

**Comment by vict0rsch** [comment]
You mean you don't want to remember tags and use the `t: your-tag` search syntax?

If that's the case I can think about it but it's going to be difficult to include seemlessly in the UI. I don't want to make the search header thicker than the current single-line

**Comment by vict0rsch** [comment]
@pviscone I've implemented a middle ground, what do you think of #121?
