### ISSUE TITLE
paper not detected popup

### ISSUE THREAD

**Issue by Roger-luo** [vict0rsch/PaperMemory#136]
**Describe the bug**
Nothing is shown in popup for https://arxiv.org/pdf/math/0502036.pdf

**To Reproduce**
1. Go to https://arxiv.org/pdf/math/0502036.pdf
2. Click on the plugin button
3. Nothing is shown

**Expected behavior**
Whatever works for other paper

**Screenshots**
<img width="1113" alt="image" src="https://user-images.githubusercontent.com/8445510/205509755-9b12da8e-4eaa-4976-9e05-f316cf9c3416.png">

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser Chrome

**Comment by vict0rsch** [comment]
Hi!

Thank you for reporting the bug.

It's not surprising since PaperMemory expects arxiv papers to match the pattern: `arxiv.org/(abs|pdf)/\d{4}\.\d{4,5}(\.pdf)?`

I'll update the code in the next version to match such papers, I was not aware of such urls existing on arxiv 😅

**Comment by Roger-luo** [comment]
Thanks for the quick response. This is a very nice package btw.

**Comment by vict0rsch** [comment]
[Thank you!](https://github.com/vict0rsch/PaperMemory/issues/81#issuecomment-1116679918)

I'll keep you posted but I expect not before Jan

**Comment by vict0rsch** [comment]
addressed in #139, will be in the next release
