### ISSUE TITLE
Taking notes of some general websites, ex. blog posts

### ISSUE THREAD

**Issue by jeasinema** [vict0rsch/PaperMemory#146]
**Is your feature request related to a problem? Please describe.**
Sometimes I just want to take some notes when reading something other than a paper, ex. a blog post about a bunch of papers. It would be cool if PaperMemory let me do this.

**Describe the solution you'd like**
Just enable PaperMemory of general webiste. I know the concern is how to properly format this entry. Actually, we can use [misc](https://www.bibtex.com/t/template-misc/) to create an entry for generic website in bibtex.

**Additional context**
Let me know what do you think!

**Comment by vict0rsch** [comment]
Hey!

I can see the usefulness and I agree.

The main blocker so far has been that everything is automated. You cannot change a paper's metadata manually except by exporting your memory, changing the json, importing back. 

In other words this suggestion would require me to implement a user interface to let you at least 1/ set the author name and 2/ the website's publication year (title and access date can be parsed automatically).

An easy v0 is to just let you record a website and only its url, title and access date would be stored. Anything else you'd have to input as a note.

As for a v1 with a user-interface, I may do this but it's not a priority.

What do you think?

Thanks for your feedback!

**Comment by jeasinema** [comment]
Hey @vict0rsch, thanks for the reply!

I think the roadmap makes perfect sense. Both v0 and v1 looks good to me.

Let me know if there is anything I can help.

**Comment by vict0rsch** [comment]
Hey @jeasinema I've but a v0/beta together in #161 

Would you like to try it out in the PR's branch and tell me if that's useful enough to be merged?

**Comment by vict0rsch** [comment]
v1's actually done too now, will be part of next release
