### ISSUE TITLE
Goodnotes 5 integration

### ISSUE THREAD

**Issue by dc914337** [vict0rsch/PaperMemory#15]
Goodnotes is an app for iPad that allows writing on pdf documents (taking notes, highlighting, etc). Really nice for reading papers.
Goodnotes 5 allows to import papers [by sending them to a dedicated email address](https://support.goodnotes.com/hc/en-us/articles/360000477276-Using-Email-to-GoodNotes-for-importing-PDF-files).
Having a button to send a paper to a preset email would be a nice hack to integrate with portable devices (i.e. iPads, androids, etc). 
An ultimate solution would be to have a WebDAV integration so that all saved papers go straight in the cloud but I guess it's harder to implement than sending an email.

**Comment by vict0rsch** [comment]
Hey @dc914337,

I don't use GoodNotes but why not. Here's the simplest thing I can think of:

1/ in the menu have a text field to store your email address
2/ on a paper's page, add a `mailto` link with your GoodNotes address

This would require you to select the pdf from the popped-up email dialog as a `mailto` link cannot include an attachment.

Note that Paper Memory does not have a backend so there's no way to use a server to send taht email _with_ the attachment. 

Would that be satisfactory to you? What browser do you use?

**Comment by vict0rsch** [comment]
Closing for now, I'll reopen if there's interest
