### ISSUE TITLE
Add option for other paper like AIP Journal

### ISSUE THREAD

**Issue by koustavpal97** [vict0rsch/PaperMemory#151]
Give a feature where user can add other Journal which might not be famous.

**Comment by vict0rsch** [comment]
Unfortunately this is not possible. Each journal will have its own API and url pattern etc. So it all has to be done manually in the source code I'm afraid

**Comment by vict0rsch** [comment]
If you have specific sources you want to include, feel free to reopen this issue and provide example papers you'd like parsed.

**Comment by koustavpal97** [comment]
AIP publication is a good publication. That can be include.
