### ISSUE TITLE
Interfering with other websites' ui

### ISSUE THREAD

**Issue by KaiFronsdalQC** [vict0rsch/PaperMemory#171]
**Describe the bug**
When enabled, PaperMemory changes the look of the icons on some websites. Specifically where I ran into this was with [chatbot-ui](https://github.com/mckaywrigley/chatbot-ui) websites. For a public facing instance (I ran into this problem on a locally hosted version), try [fastgpt.app](https://www.fastgpt.app/). If you enable the extension, you will notice that the icons on the webpage become large and blue when enabled.

**To Reproduce**
1. Disable PaperMemory extension
2. Go to https://www.fastgpt.app/
3. Icons are normal sized and white
4. Enable PaperMemory extension
5. Icons are large and blue

**Expected behavior**
Icons on non-arxiv/paper websites should not be altered.

**Screenshots**
The normal chatbot ui:
![Normal Chatbot UI](https://github.com/vict0rsch/PaperMemory/assets/137222625/8ef6004d-8040-4a81-a953-dd7df9193acb)
Chatbot ui with papermemory enabled:
![Altered Chatbot UI](https://github.com/vict0rsch/PaperMemory/assets/137222625/fb02e33d-40d9-40c3-9a19-2a030c5e2f65)

**Desktop (please complete the following information):**
 - OS: Macos
 - Browser: Firefox
 - Version: 115.0.2
- PaperMemory version: 0.5.11

**Comment by vict0rsch** [comment]
Thanks for reporting ; I'll have a look in a couple weeks. Sorry for the inconvenience in the meantime

**Comment by vict0rsch** [comment]
Fixed it! I was using the default class names for the `tabler` icons I use in PaperMemory and so do they so there was an interference. I've updated the CSS class names and released a new version. It's pending approval by the Chrome Webstore but should be available (and automatically updated on your device) soon

**Comment by vict0rsch** [comment]
Thank you for reporting!
