### ISSUE TITLE
Bib matcher failing when using unpaywall.org

### ISSUE THREAD

**Issue by Pangasius** [vict0rsch/PaperMemory#194]
**Describe the bug**
Paper matching hangs when trying to match on unpaywall.org

![image](https://github.com/vict0rsch/PaperMemory/assets/43137887/b700fca7-09ff-4468-9439-1017427818fa)

**To Reproduce**
1) Go to bibmatcher
2) Paste a bibliography, for example this one :
@article{DBLP:journals/corr/abs-2307-02486,
  author       = {Jiayu Ding and
                  Shuming Ma and
                  Li Dong and
                  Xingxing Zhang and
                  Shaohan Huang and
                  Wenhui Wang and
                  Nanning Zheng and
                  Furu Wei},
  title        = {LongNet: Scaling Transformers to 1, 000, 000, 000 Tokens},
  journal      = {CoRR},
  volume       = {abs/2307.02486},
  year         = {2023},
  url          = {https://doi.org/10.48550/arXiv.2307.02486},
  doi          = {10.48550/arXiv.2307.02486},
  eprinttype    = {arXiv},
  eprint       = {2307.02486},
  timestamp    = {Thu, 03 Aug 2023 08:59:39 +0200},
  biburl       = {https://dblp.org/rec/journals/corr/abs-2307-02486.bib},
  bibsource    = {dblp computer science bibliography, https://dblp.org}
}
3) Run matcher with default parameters

4) Watch it hang forever on this
![image](https://github.com/vict0rsch/PaperMemory/assets/43137887/2a875902-b4b1-4c86-9ddf-4a4234bc9220)

**Expected behavior**
Supposed to match and continue in case it crashes / doesn't find anything ? I suppose.

**Desktop:**
 - OS: Windows
 - Browser: Brave
 - Version: 1.61.109
- PaperMemory version: 0.7.0

**Idea for a fix**
So simply change line 202 in src/bibMatcher/bibMatcher.js from
```
        venue = match.venue;
```
to
```
        venue = match?.venue;
```

Since it looks like the same mistake is on line 186 I added it too, now it runs fine.

![image](https://github.com/vict0rsch/PaperMemory/assets/43137887/4a74511a-bea0-4101-a3db-fa02feae7c32)

**Additional notes:**
I am not at all familiar with .js, maybe it was intended not to gave the "?." but from my experience with flutter I suppose it would not hurt to add it.

Also I did not make a pull request because I am not familiar with the rest of the code and maybe the exception should be handled elsewhere.

**Comment by vict0rsch** [comment]
Hi! Thanks for your feedback. I'll fix this next week and release an update!
