### ISSUE TITLE
no reaction after clicking the PaperMemory button

### ISSUE THREAD

**Issue by UltronAI** [vict0rsch/PaperMemory#27]
Hi, @vict0rsch ,

Thanks for your great work! I have tried your PaperMemory and find it pretty useful!

However, I don't know if it only happens to me that the panel will not appear or slowly after I click the PaperMemory button.

Is it a bug to be fixed or optimized?

Sincerely,
Feng Gao

**Comment by vict0rsch** [comment]
Thanks for the issue, can you tell me a little more: os, browser, PM version?

**Comment by UltronAI** [comment]
OS: macOS 12.0.1
Browser: Chrome 96.0.4664.55
PM: 0.3.3

Thanks for your quick reply!

**Comment by UltronAI** [comment]
Hmm, I find it possibly related to my poor internet connection and now it's better. 

I'll try more but it works currently! Thanks!

**Comment by vict0rsch** [comment]
Ok, keep me posted!

![2021-11-29 08 47 38](https://user-images.githubusercontent.com/9283470/143879467-848b6c9e-9fc7-4dc2-9baa-938f01316d0f.gif)

If you think you have a bug again you can look in the console for errors
