### ISSUE TITLE
Auto tagging from user regex

### ISSUE THREAD

**Issue by vict0rsch** [vict0rsch/PaperMemory#33]
idea: create an options page to have more room to deal with it (or use a modal?) and allow the user to provide pairs `(regex, tag)` for PaperMemory to auto tag papers based on titles

**Comment by QiuJueqin** [comment]
Hi, how can I customize PDF file renaming rule? Can I capture first author name and published date as keys, e.g. `InstaGAN Instance-aware Image-to-Image Translation_Mo_2019.pdf`?

**Comment by vict0rsch** [comment]
Different issue, I created https://github.com/vict0rsch/PaperMemory/issues/35

**Comment by vict0rsch** [comment]
Implemented in #38
