### ISSUE TITLE
Make notifications for "Paper Added" optional

### ISSUE THREAD

**Issue by amitness** [vict0rsch/PaperMemory#39]
When visiting a new paper that's not added to the memory, the extension currently shows a notification-like popup on the right side that the paper was added to memory. This feels distracting to me and I would just like the extension to work behind the scenes.

I was wondering if you could add a setting in the extension options where we can turn off the notifications.

**Comment by vict0rsch** [comment]
Hey, thanks for your feedback. 

Can you share an example paper url? The notification should only popup if the paper _is_ added, not if it's not so it sounds like there is an error in the code that prevents that paper to be actually added

**Comment by amitness** [comment]
@vict0rsch Hey, sorry for the confusion. The notification popup works correctly and doesn't show up for already added papers. It is only shown if the paper is added the first time.

What I requested above was a toggle to enable/disable notifications on the right side for new papers completely.

**Comment by vict0rsch** [comment]
Oh! It's already there, check out the popup's menu
<img width="429" alt="2021-12-10 at 15 38" src="https://user-images.githubusercontent.com/9283470/145591217-f25a6e32-988f-44f1-bacb-727133acde7f.png">

**Comment by amitness** [comment]
My bad. I was looking at the extension options and didn't realize you had that setting in the popup menu.

Thank you so much for working on this extension. It's very useful.

![image](https://user-images.githubusercontent.com/8587189/145593038-f292933b-e139-4e76-8e1a-44ecc01acea8.png)

**Comment by vict0rsch** [comment]
I'll rename the "Options" page to "Advanced Options" and refer to the popup's menu there too, if you missed it, it was not clear :)
