### ISSUE TITLE
Add link to SciRate as well

### ISSUE THREAD

**Issue by k4rtik** [vict0rsch/PaperMemory#46]
**Is your feature request related to a problem? Please describe.**
I often like to go to the paper's scirate.com page when I stumble upon an arXiv paper to see what others in the community think of it or to rate it myself.

**Describe the solution you'd like**
SciRate pages are linked as, e.g. for https://arxiv.org/pdf/2112.10677.pdf -> https://scirate.com/arxiv/2112.10677 I use this extension for switching between PDF and response page all the time, it will be nice to also have a button to take me to the corresponding SciRate page.

**Additional context**
NA

**Comment by vict0rsch** [comment]
Hey @k4rtik ! 

Thanks for the suggestion, this sounds reasonable. Not sure how much SciRate is used but here's what I suggest to do:

1/ Add an option in the menu to enable scirate links
2/ When you are on an arxiv paper, if the above option is On then add a button to redirect you to scirate

Questions:

a/ Do you think you'd need that as an extra button in the Memory list too? Keep in mind that it would make yet another element in that line which may get messy to read...

b/ would you rather have the scirate link opened in a new tab or the current one?

**Comment by k4rtik** [comment]
Hi @vict0rsch 

Thanks so much for considering this feature. SciRate is used quite a lot by the people interested in the pretty large quant-ph arXiv class.

1 and 2 sound good.

a. I don't care about the memory option, I installed the extension when it did not have any memory features (before it was renamed). I use scirate to bookmark the interesting arxiv papers instead.
b. Whatever is easier. I think it will not hurt to have the current tab open the scirate link as the scirate page has direct links to both the response page and the PDF.

**Comment by vict0rsch** [comment]
Done in #49 and with release 4.3 which has been uploaded to the online stores, your extension should auto-update in the coming hours!
