### ISSUE TITLE
BPP Mozilla submit error

### ISSUE THREAD

**Issue by vict0rsch** [vict0rsch/PaperMemory#53]
In https://github.com/vict0rsch/PaperMemory/runs/5352857182?check_suite_focus=true#step:3:12 there's an error with the extension id.

In the `secrets` I put `"extId": "paper-memory"` in the `"firefox"` field. Maybe the `extId` is actually what's called the `UUID` in the Mozilla addons dev tools?

That being said, the Chrome submission worked! Thanks so much for #51 @louisgv :)

**Comment by louisgv** [comment]
Yes, the extId for Mozilla store is the UUID string. However, if you specified it in your manifest under gecko.id (see: https://extensionworkshop.com/documentation/develop/extensions-and-the-add-on-id/ ), you would need to omit the extId in the secrets :)

**Comment by vict0rsch** [comment]
Ok! I'll check with the next release. Feel free to suggest improvements
