### ISSUE TITLE
Only one paper is saved when opening multiple papers at the same time

### ISSUE THREAD

**Issue by kaixin96** [vict0rsch/PaperMemory#62]
**Describe the bug**

When I open multiple papers from a bookmark folder at the same time (i.e. using "open all tabs in a new window"), only the paper in the first tab is saved.

**To Reproduce**
1. Go to the bookmark manager
2. Right click on a folder and select "open all in a new window" 
3. Other tabs except the first one are not saved

**Expected behavior**
All tabs are saved.

**Desktop (please complete the following information):**
 - OS: macOS Monterey
 - Browser: Chrome
 - Version: 99.0.4844.51
- PaperMemory version: 0.4.4.1

Thank you!

**Comment by vict0rsch** [comment]
I just tried and I get the same behaviour. This is super surprising considering the content scripts are indeed executed.

<img width="1680" alt="2022-03-28 at 11 27" src="https://user-images.githubusercontent.com/9283470/160368944-c678e4e7-1b59-431f-9d91-eb4e2ec7f36d.png">
 
I'll try to debug. How critical is this?

**Comment by vict0rsch** [comment]
Actually the behaviour I observe is slightly different: it's not necessarily the first that is added, it can be 1 or 2 random ones 😩

**Comment by vict0rsch** [comment]
Ok I think I have an idea: the storage update is an async operation so there's no guarantee in the order papers from a folder will be added. 

PaperMemory loads all the papers in the content script's `global.state.papers` object and overwrites the storage's `"papers"` key with the new paper. Here's the likely toy scenario of what's hapenning:

* PM loads all `papers`
* PM discovers `paper1`
* PM fetches data for `paper1`
* PM discovers `paper2`
* PM fetches data for `paper2`
* PM receives data for `paper2` faster
* PM updates the storage `papers` with the new `paper2`
* PM receives data for `paper1`
* PM updates the storage `papers` with the new `paper1`
  * Issue: at that stage the process handling `paper1` is not aware of `paper2` so the `papers` object saved to storage _does not contain `paper2`_ and so it seems that PM did not detect it

**Comment by vict0rsch** [comment]
As of now there's no way around that theoretical issue. I will try to shrink the window for that issue to arise but I cannot make it disappear: it is due to the fact that the storage API does not allow for update operations, rather read -> in-memory update -> write which leaves some millisecs for issues...

**Comment by vict0rsch** [comment]
The fix I implemented raised the number of retrieved papers from `2/17` to `12/17` so I think I'll leave it there for the next version. 

Is there any other scenario in your opinion than the one-off addition of an entire bookmark folder to PM? Also, is refreshing manually those tabs prohibitively annoying or are you happy with an improvement-which-is-not-a-fix ?

**Comment by kaixin96** [comment]
Thank you very much for the quick reply and fix!

Yes, it can be random. Later I found it is not necessarily the first tab.

I believe this is a rare use case. The only scenario I can think of is importing a large number of entries (in my case 1000+). Maybe it would be better to have an option to directly importing from a list of titles/urls without actually opening tabs. But that is not urgent.

I am ok with leaving it. It is not a critical issue. If the new fix hurts speed/performance, I think it is ok to revert it. Previously I was just wondering if there is any easy fix.

In case anyone also wants to do such migration, my workaround is using python ([webbrowser](https://docs.python.org/3/library/webbrowser.html)) to automate the page opening process and wait for 5 secs between two urls (giving PM sufficient time to finish its job).
