### ISSUE TITLE
Configuration option to disable auto-add to memory and manually adding paper to memory

### ISSUE THREAD

**Issue by MayankAgarwal** [vict0rsch/PaperMemory#71]
**Is your feature request related to a problem? Please describe.**
- Sometimes I open a paper page just to quickly browse and then decide to not read it.
- PaperMemory, however, automatically adds the paper to the store, which over time could accumulate unwanted papers in there.

**Describe the solution you'd like**
- A configuration option to disable automatically adding papers to the memory
- A button to explicitly add a paper to memory. This would be required if a user has turned off automatically adding paper to memory, and then wants to add a certain paper in there.

**Comment by vict0rsch** [comment]
Thank you for your feedback. This is definitely technically possible. Now the may question is user experience and interface. I'll think of a way to make it smooth. I'll keep you posted.

In the mean time, notice there's a Trash icon in the notification which you can use to delete the paper that was just added

**Comment by MayankAgarwal** [comment]
Thank you! I agree that maintaining the user experience needs some thought.
Also, having used it for a few hours just wanted to thank you for this wonderful plugin. It has already reduced the number of open tabs in my browser 😄

**Comment by vict0rsch** [comment]
Also @MayankAgarwal you can use the option to disable parsing from non-pdf pages
<img width="426" alt="2022-04-22 at 16 12" src="https://user-images.githubusercontent.com/9283470/164731947-c16a1003-6a0f-492a-b891-c3d922404d82.png">

**Comment by vict0rsch** [comment]
@MayankAgarwal can you [install from source (branch `master`)](https://github.com/vict0rsch/PaperMemory#install-from-source-brave--chrome) and check that it does what you expect?

**Comment by MayankAgarwal** [comment]
Hi @vict0rsch : I just checked the feature and it looks great! Thanks :)

**Comment by vict0rsch** [comment]
Cool! Did you get the message about the shortcut when you did?
