### ISSUE TITLE
Citation in MLA or APA style format 

### ISSUE THREAD

**Issue by iiscleap** [vict0rsch/PaperMemory#77]
It will be great if we can copy citation in MLA or APA style format as well.

- Short author info, published venue and year can be added to the In markdown format.

**Comment by vict0rsch** [comment]
Hey! Thanks for your feedback and ideas.

I'll think about the markdown feature and try it out to see if it should be standard or customizable.

Regarding citations, it would be difficult I think to keep it both simple, flexible and user friendly. I'll give it more thoughts but for now I'd recommend using other conversion options such as online tools or processing the bib export you can get in the advanced options page

**Comment by iiscleap** [comment]
Yes, that markdown format customization feature will be enough :)
Thank you.

**Comment by vict0rsch** [comment]
How about #83 ? WOuld that work for you?
