### ISSUE TITLE
Google UI partially breaks when using extension

### ISSUE THREAD

**Issue by JorenB** [vict0rsch/PaperMemory#86]
Icons in both the GMail and Google Calendar web interfaces get squeezed or misaligned when PaperMemory is activated.

**Desktop (please complete the following information):**
 - OS: MacOS Monterey
 - Browser chrome
 - Version 100
- PaperMemory version 0.5.2
<img width="747" alt="Screenshot 2022-05-04 at 18 25 27" src="https://user-images.githubusercontent.com/642573/166726800-401fd9f6-77c6-43ff-b445-a15c425489b3.png">
<img width="79" alt="Screenshot 2022-05-04 at 18 25 52" src="https://user-images.githubusercontent.com/642573/166726865-42f22e66-7c4c-4ee6-9eb1-5d3420703d74.png">

**Comment by vict0rsch** [comment]
Interesting I noticed the same thing on my computer but had not realized it was PM's fault. Thank you for reporting I'll investigate

**Comment by vict0rsch** [comment]
Ok found it I changed the content scripts' css it'll show in the next release. Or you can install from source in the mean time
