### ISSUE TITLE
Allow importing entries in the same format as those exported

### ISSUE THREAD

**Issue by jeasinema** [vict0rsch/PaperMemory#89]
**Is your feature request related to a problem? Please describe.**
Since we can export the papers and our notes in `.json`. I find it a good idea to allow us to import them as well. That can help bring us some users from other bib management software, ex. Mendeley, Paperpile, etc.

**Describe the solution you'd like**
It should be straightforward -- just a simple sanity check on the format of the imported JSON file and reject those that are not compliant. 

**Additional context**
That said, I cannot find the interface to export my entries tho.

**Comment by vict0rsch** [comment]
## Version `0.5.2`

Have you seen this part of the options page?

<img width="778" alt="2022-05-05 at 08 24" src="https://user-images.githubusercontent.com/9283470/166873045-e86d0714-56a7-44ff-ad50-af32226fd240.png">

It should allow you to both export then import your Memory as `.json` files with sanity checks.

You can access it from the extension's popup menu:

<img width="448" alt="2022-05-05 at 08 33" src="https://user-images.githubusercontent.com/9283470/166873109-7d653afb-9269-40c5-b674-26230ab1ee0f.png">

Or `Right click + Options`:

<img width="376" alt="2022-05-05 at 08 34" src="https://user-images.githubusercontent.com/9283470/166873203-64cc1190-f74d-4fab-aff5-6de027149f8f.png">

## Version `0.5.3`

This is not released just yet but available [from source](https://github.com/vict0rsch/PaperMemory#install-from-source-brave--chrome) but there will be a feature to import a list of papers as per #75 (the difference is that a raw list of papers requires parsing, *i.e.* retrieving a paper's authors, title etc. as well as matching preprints to publications databases

**Comment by vict0rsch** [comment]
I'll close as I believe it answers your issue but feel free to re-open

**Comment by jeasinema** [comment]
Thank you!

**Comment by vict0rsch** [comment]
As of `0.5.3`:

<img width="968" alt="2022-05-05 at 11 17" src="https://user-images.githubusercontent.com/9283470/166895130-d78f9ed9-d423-4ad1-a567-db14f3a75ecf.png">
