### ISSUE TITLE
Submit workflow hangs

### ISSUE THREAD

**Issue by vict0rsch** [vict0rsch/PaperMemory#93]
@louisgv any idea why this hangs forever? https://github.com/vict0rsch/PaperMemory/actions/runs/2282307207

**Comment by vict0rsch** [comment]
Looks like signing is not finishing 

```
Signing add-on [ .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  . ]
```

**Comment by vict0rsch** [comment]
It seems the Chrome Webstore submission went through

**Comment by vict0rsch** [comment]
There was an issue in the manifest, Firefox _requires_ `"suggested_key"` to be an `object` while Chrome accepts a `string`. I'm going to assume it was it.

**Comment by louisgv** [comment]
@vict0rsch  is Firefox submission works now or is the manifest conflict still preventing it from finishing?

**Comment by vict0rsch** [comment]
Looks like that was the issue, it's working for the latest release https://github.com/vict0rsch/PaperMemory/actions/runs/2300869446
