### ISSUE TITLE
Change the text alignment on Google Calendar

### ISSUE THREAD

**Issue by Zhehui-Huang** [vict0rsch/PaperMemory#94]
When I enable the PaperMemory extension on Google Chrome, my Google Calendar will be Changed. Specifically, the text of the name of the calendar will not be well-aligned.

**Comment by vict0rsch** [comment]
Hey!

I thought I had fixed this in #86 which is part of the `0.5.3` release.

Can you tell me the PaperMemory version you're using and if it's not the latest can you update and check the problem persists?

**Comment by vict0rsch** [comment]
I'm going to assume this is not an issue anymore and there was a lag in the auto-update of the extension. Feel free to re-open if the problem persists
